# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Moodle (front end) dev
email: ssrjuliarietveld@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Modern Moodle 3+ web dev with focus on beautiful and user friendly front end.
baseurl: "/moodle_dev" # the subpath of your site, e.g. /blog
url: "https:/juliarietveld.github.io/" # the base hostname & protocol for your site
lang: en # specify content language
github_username:  JuliaRietveld

# Build settings
markdown: kramdown
exclude: ["src",
          "test",
          "node_modules",
          "package.json"] # Don't forget that Jekyll automatically
                          # excludes files with a dot prefix
compress_html:
  clippings: []
  comments: []
  endings: []
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: []

theme: jekyll-theme-cayman